[package]
name = "rs-cnc"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
base64 = "0.21.0"
bytes = "1.3.0"
hex = "0.4.3"
rand = "0.8.5"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.38"

[dev-dependencies]
tokio = { version = "1.24.2", features = ["full"] }
